// Kernel Function: paged_proj__windowed
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void paged_proj__windowed(__gm__ bfloat16_t* v1, __gm__ bfloat16_t* v2, __gm__ float* v3, int32_t v4) {
  unsigned v5 = 0;
  const int32_t v6 = 64;
  const int32_t v7 = 0;
  const int32_t v8 = 128;
  const int32_t v9 = 256;
  const int32_t v10 = 1;
  const int32_t v11 = 2048;
  const int32_t v12 = 16;
  const int64_t v13 = 2048;
  const int64_t v14 = 32768;
  const int64_t v15 = 4096;
  const int64_t v16 = 0;
  using T = float;

  #if defined(__DAV_CUBE__)
  size_t v17 = (size_t) v10;
  Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v18 = Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v8);
  uint64_t v19 = (uint64_t) v16;
  TASSIGN(v18, v19);
  pto::Shape<1, 1, 1, 16, 128> v20 = pto::Shape<1, 1, 1, 16, 128>();
  pto::Stride<32768, 32768, 32768, 2048, 1> v21 = pto::Stride<32768, 32768, 32768, 2048, 1>();
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<32768, 32768, 32768, 2048, 1>, pto::Layout::ND> v22 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<32768, 32768, 32768, 2048, 1>, pto::Layout::ND>(v1 + (v5 + v5 * (unsigned) v11 + v5 * (unsigned) v10), v20, v21);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  TLOAD(v18, v22);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  Tile<TileType::Mat, bfloat16_t, 128, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v23 = Tile<TileType::Mat, bfloat16_t, 128, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v8, v9);
  uint64_t v24 = (uint64_t) v15;
  TASSIGN(v23, v24);
  pto::Shape<1, 1, 1, 128, 256> v25 = pto::Shape<1, 1, 1, 128, 256>();
  pto::Stride<32768, 32768, 32768, 256, 1> v26 = pto::Stride<32768, 32768, 32768, 256, 1>();
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 256>, pto::Stride<32768, 32768, 32768, 256, 1>, pto::Layout::ND> v27 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 256>, pto::Stride<32768, 32768, 32768, 256, 1>, pto::Layout::ND>(v2 + (v5 + v5 * (unsigned) v9 + v5 * (unsigned) v10), v25, v26);
  TLOAD(v23, v27);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
  Tile<TileType::Left, bfloat16_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v28 = Tile<TileType::Left, bfloat16_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v6);
  uint64_t v29 = (uint64_t) v16;
  TASSIGN(v28, v29);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  TEXTRACT(v28, v18, v7, v7);
  Tile<TileType::Right, bfloat16_t, 64, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v30 = Tile<TileType::Right, bfloat16_t, 64, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v6, v9);
  uint64_t v31 = (uint64_t) v14;
  TASSIGN(v30, v31);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
  TEXTRACT(v30, v23, v7, v7);
  set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
  Tile<TileType::Left, bfloat16_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v32 = Tile<TileType::Left, bfloat16_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v6);
  uint64_t v33 = (uint64_t) v13;
  TASSIGN(v32, v33);
  TEXTRACT(v32, v18, v7, v6);
  Tile<TileType::Right, bfloat16_t, 64, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Right, bfloat16_t, 64, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v6, v9);
  uint64_t v35 = (uint64_t) v16;
  TASSIGN(v34, v35);
  TEXTRACT(v34, v23, v6, v7);
  set_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  Tile<TileType::Acc, float, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Acc, float, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
  uint64_t v37 = (uint64_t) v16;
  TASSIGN(v36, v37);
  wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
  TMATMUL(v36, v28, v30);
  Tile<TileType::Acc, float, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Acc, float, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
  uint64_t v39 = (uint64_t) v16;
  TASSIGN(v38, v39);
  pipe_barrier(PIPE_M);
  wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
  TMATMUL_ACC(v38, v38, v32, v34);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  for (size_t v40 = v17; v40 < ((size_t) v12); v40 += v17) {
    int32_t v41 = (int32_t) ((uint32_t) ((int32_t) v40) * (uint32_t) v8);
    Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v42 = Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v8);
    uint64_t v43 = (uint64_t) v16;
    TASSIGN(v42, v43);
    pto::Shape<1, 1, 1, 16, 128> v44 = pto::Shape<1, 1, 1, 16, 128>();
    pto::Stride<32768, 32768, 32768, 2048, 1> v45 = pto::Stride<32768, 32768, 32768, 2048, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<32768, 32768, 32768, 2048, 1>, pto::Layout::ND> v46 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<32768, 32768, 32768, 2048, 1>, pto::Layout::ND>(v1 + (v5 + v5 * (unsigned) v11 + (unsigned) v41 * (unsigned) v10), v44, v45);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
    TLOAD(v42, v46);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
    Tile<TileType::Mat, bfloat16_t, 128, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Mat, bfloat16_t, 128, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v8, v9);
    uint64_t v48 = (uint64_t) v15;
    TASSIGN(v47, v48);
    pto::Shape<1, 1, 1, 128, 256> v49 = pto::Shape<1, 1, 1, 128, 256>();
    pto::Stride<32768, 32768, 32768, 256, 1> v50 = pto::Stride<32768, 32768, 32768, 256, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 256>, pto::Stride<32768, 32768, 32768, 256, 1>, pto::Layout::ND> v51 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 256>, pto::Stride<32768, 32768, 32768, 256, 1>, pto::Layout::ND>(v2 + (v5 + (unsigned) v41 * (unsigned) v9 + v5 * (unsigned) v10), v49, v50);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
    TLOAD(v47, v51);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
    Tile<TileType::Left, bfloat16_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Left, bfloat16_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v53 = (uint64_t) v16;
    TASSIGN(v52, v53);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    TEXTRACT(v52, v42, v7, v7);
    Tile<TileType::Right, bfloat16_t, 64, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Right, bfloat16_t, 64, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v6, v9);
    uint64_t v55 = (uint64_t) v14;
    TASSIGN(v54, v55);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
    TEXTRACT(v54, v47, v7, v7);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
    Tile<TileType::Left, bfloat16_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Left, bfloat16_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v57 = (uint64_t) v13;
    TASSIGN(v56, v57);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
    TEXTRACT(v56, v42, v7, v6);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
    Tile<TileType::Right, bfloat16_t, 64, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Right, bfloat16_t, 64, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v6, v9);
    uint64_t v59 = (uint64_t) v16;
    TASSIGN(v58, v59);
    TEXTRACT(v58, v47, v6, v7);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
    Tile<TileType::Acc, float, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Acc, float, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
    uint64_t v61 = (uint64_t) v16;
    TASSIGN(v60, v61);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
    pipe_barrier(PIPE_M);
    TMATMUL_ACC(v60, v60, v52, v54);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    Tile<TileType::Acc, float, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Acc, float, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
    uint64_t v63 = (uint64_t) v16;
    TASSIGN(v62, v63);
    pipe_barrier(PIPE_M);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
    TMATMUL_ACC(v62, v62, v56, v58);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  }
  set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 256> v64 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v65 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v66 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v3 + (v5 + v5 * (unsigned) v9 + v5 * (unsigned) v10), v64, v65);
  wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  TSTORE(v66, v38);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  #endif // __DAV_CUBE__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: x_page__ssa_v0
    __gm__ Tensor* x_page__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* x_page__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(x_page__ssa_v0_tensor->buffer.addr) + x_page__ssa_v0_tensor->start_offset;

    // Unpack tensor: w1__ssa_v0
    __gm__ Tensor* w1__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ bfloat16_t* w1__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(w1__ssa_v0_tensor->buffer.addr) + w1__ssa_v0_tensor->start_offset;

    // Unpack tensor: paged_y__iter_v1
    __gm__ Tensor* paged_y__iter_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* paged_y__iter_v1 = reinterpret_cast<__gm__ float*>(paged_y__iter_v1_tensor->buffer.addr) + paged_y__iter_v1_tensor->start_offset;

    // Unpack scalar: m0__ssa_v0
    union { uint64_t u64; int64_t val; } m0__ssa_v0_conv;
    m0__ssa_v0_conv.u64 = args[3];
    int64_t m0__ssa_v0 = m0__ssa_v0_conv.val;

    // Forward to ptoas-generated function
    paged_proj__windowed(x_page__ssa_v0, w1__ssa_v0, paged_y__iter_v1, m0__ssa_v0);
}
