// Orchestration Function: paged_consumer_block_table
// Generated by PyPTO IR Compiler

#include "runtime.h"
#include <iostream>

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "pto_orchestration_api.h"

extern "C" {

__attribute__((visibility("default")))
PTO2OrchestrationConfig aicpu_orchestration_config(const ChipStorageTaskArgs& orch_args) {
    (void)orch_args;
    return PTO2OrchestrationConfig{
        .expected_arg_count = 5,
    };
}

__attribute__((visibility("default")))
void aicpu_orchestration_entry(const ChipStorageTaskArgs& orch_args) {
    // External tensors
    Tensor ext_x = from_tensor_arg(orch_args.tensor(0));
    Tensor ext_w1 = from_tensor_arg(orch_args.tensor(1));
    Tensor ext_gamma = from_tensor_arg(orch_args.tensor(2));
    Tensor ext_block_table = from_tensor_arg(orch_args.tensor(3));
    Tensor ext_out = from_tensor_arg(orch_args.tensor(4));

    PTO2_SCOPE() {
        uint32_t paged_y_ci_shapes[2] = {256, 256};
        TensorCreateInfo paged_y_ci(paged_y_ci_shapes, 2, DataType::FLOAT32);
        TaskOutputTensors alloc_0 = alloc_tensors(paged_y_ci);
        const Tensor& paged_y = alloc_0.get_ref(0);
        for (int64_t ob = 0; ob < 16; ob += 1) {
            PTO2_SCOPE() {
                int64_t m0 = (ob * 16);
                uint32_t x_page_offsets[2] = {static_cast<uint32_t>(m0), 0};
                uint32_t x_page_shapes[2] = {(x_page_offsets[0] >= ext_x.shapes[0] ? 0u : std::min<uint32_t>(16, ext_x.shapes[0] - x_page_offsets[0])), (x_page_offsets[1] >= ext_x.shapes[1] ? 0u : std::min<uint32_t>(2048, ext_x.shapes[1] - x_page_offsets[1]))};
                Tensor x_page = ext_x.view(x_page_shapes, x_page_offsets);
                uint32_t paged_y__iter_v1__window_offsets[2] = {static_cast<uint32_t>(m0), 0};
                uint32_t paged_y__iter_v1__window_shapes[2] = {(paged_y__iter_v1__window_offsets[0] >= paged_y.shapes[0] ? 0u : std::min<uint32_t>(16, paged_y.shapes[0] - paged_y__iter_v1__window_offsets[0])), (paged_y__iter_v1__window_offsets[1] >= paged_y.shapes[1] ? 0u : std::min<uint32_t>(256, paged_y.shapes[1] - paged_y__iter_v1__window_offsets[1]))};
                Tensor paged_y__iter_v1__window = paged_y.view(paged_y__iter_v1__window_shapes, paged_y__iter_v1__window_offsets);

                // Task 0: paged_proj__windowed
                Arg params_t0;
                params_t0.add_input(x_page);
                params_t0.add_input(ext_w1);
                params_t0.add_output(paged_y__iter_v1__window);
                params_t0.add_scalar(m0);
                rt_submit_aic_task(0, params_t0);
                const Tensor& paged_y__ssa_v3__windowed = paged_y__iter_v1__window;
            }
        }
        for (int64_t ob = 0; ob < 16; ob += 1) {
            PTO2_SCOPE() {
                uint32_t indices_t[1] = {static_cast<uint32_t>(ob)};
                int32_t t = get_tensor_data<int32_t>(ext_block_table, 1, indices_t);
                int64_t page_id = static_cast<int64_t>(t);
                int64_t src_row = (page_id * 16);
                int64_t out_m0 = (ob * 16);
                uint32_t y_src_offsets[2] = {static_cast<uint32_t>(src_row), 0};
                uint32_t y_src_shapes[2] = {(y_src_offsets[0] >= paged_y.shapes[0] ? 0u : std::min<uint32_t>(16, paged_y.shapes[0] - y_src_offsets[0])), (y_src_offsets[1] >= paged_y.shapes[1] ? 0u : std::min<uint32_t>(256, paged_y.shapes[1] - y_src_offsets[1]))};
                Tensor y_src = paged_y.view(y_src_shapes, y_src_offsets);
                uint32_t out__iter_v1__window_offsets[2] = {static_cast<uint32_t>(out_m0), 0};
                uint32_t out__iter_v1__window_shapes[2] = {(out__iter_v1__window_offsets[0] >= ext_out.shapes[0] ? 0u : std::min<uint32_t>(16, ext_out.shapes[0] - out__iter_v1__window_offsets[0])), (out__iter_v1__window_offsets[1] >= ext_out.shapes[1] ? 0u : std::min<uint32_t>(256, ext_out.shapes[1] - out__iter_v1__window_offsets[1]))};
                Tensor out__iter_v1__window = ext_out.view(out__iter_v1__window_shapes, out__iter_v1__window_offsets);

                // Task 1: paged_rmsnorm__windowed
                Arg params_t1;
                params_t1.add_input(ext_gamma);
                params_t1.add_input(y_src);
                params_t1.add_output(out__iter_v1__window);
                params_t1.add_scalar(out_m0);
                rt_submit_aiv_task(1, params_t1);
                const Tensor& out__ssa_v3__windowed = out__iter_v1__window;
            }
        }
    }
}

}  // extern "C"
