// Kernel Function: paged_rmsnorm__windowed
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void paged_rmsnorm__windowed(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, int32_t v4) {
  unsigned v5 = 0;
  const float v6 = 9.99999997E-7f;
  const float v7 = 0.00390625f;
  const int32_t v8 = 16;
  const int32_t v9 = 256;
  const int32_t v10 = 1;
  const int64_t v11 = 50240;
  const int64_t v12 = 50176;
  const int64_t v13 = 33792;
  const int64_t v14 = 17408;
  const int64_t v15 = 16384;
  const int64_t v16 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v17 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v9);
  uint64_t v18 = (uint64_t) v16;
  TASSIGN(v17, v18);
  pto::Shape<1, 1, 1, 16, 256> v19 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v20 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v21 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v2 + (v5 + v5 * (unsigned) v9 + v5 * (unsigned) v10), v19, v20);
  TLOAD(v17, v21);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v22 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v23 = (uint64_t) v15;
  TASSIGN(v22, v23);
  pto::Shape<1, 1, 1, 1, 256> v24 = pto::Shape<1, 1, 1, 1, 256>();
  pto::Stride<256, 256, 256, 256, 1> v25 = pto::Stride<256, 256, 256, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<256, 256, 256, 256, 1>, pto::Layout::ND> v26 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<256, 256, 256, 256, 1>, pto::Layout::ND>(v1 + (v5 + v5 * (unsigned) v9 + v5 * (unsigned) v10), v24, v25);
  TLOAD(v22, v26);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v27 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v9);
  uint64_t v28 = (uint64_t) v14;
  TASSIGN(v27, v28);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TMUL(v27, v17, v17);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v29 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v9);
  uint64_t v30 = (uint64_t) v13;
  TASSIGN(v29, v30);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v31 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v10);
  uint64_t v32 = (uint64_t) v12;
  TASSIGN(v31, v32);
  TROWSUM(v31, v27, v29);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v33 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v8);
  uint64_t v34 = (uint64_t) v12;
  TASSIGN(v33, v34);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v35 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v8);
  uint64_t v36 = (uint64_t) v11;
  TASSIGN(v35, v36);
  pipe_barrier(PIPE_V);
  TMULS(v35, v33, v7);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v37 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v8);
  uint64_t v38 = (uint64_t) v11;
  TASSIGN(v37, v38);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v39 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v8);
  uint64_t v40 = (uint64_t) v11;
  TASSIGN(v39, v40);
  pipe_barrier(PIPE_V);
  TADDS(v39, v37, v6);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v8);
  uint64_t v42 = (uint64_t) v11;
  TASSIGN(v41, v42);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v8);
  uint64_t v44 = (uint64_t) v11;
  TASSIGN(v43, v44);
  pipe_barrier(PIPE_V);
  TRSQRT(v43, v41);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v10);
  uint64_t v46 = (uint64_t) v11;
  TASSIGN(v45, v46);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v9);
  uint64_t v48 = (uint64_t) v16;
  TASSIGN(v47, v48);
  pipe_barrier(PIPE_V);
  TROWEXPANDMUL(v47, v17, v45);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v49 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v9);
  uint64_t v50 = (uint64_t) v16;
  TASSIGN(v49, v50);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TCOLEXPANDMUL(v49, v47, v22);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 256> v51 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v52 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v53 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v3 + (v5 + v5 * (unsigned) v9 + v5 * (unsigned) v10), v51, v52);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v53, v49);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: gamma__ssa_v0
    __gm__ Tensor* gamma__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* gamma__ssa_v0 = reinterpret_cast<__gm__ float*>(gamma__ssa_v0_tensor->buffer.addr) + gamma__ssa_v0_tensor->start_offset;

    // Unpack tensor: y_src__ssa_v0
    __gm__ Tensor* y_src__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* y_src__ssa_v0 = reinterpret_cast<__gm__ float*>(y_src__ssa_v0_tensor->buffer.addr) + y_src__ssa_v0_tensor->start_offset;

    // Unpack tensor: out__iter_v1
    __gm__ Tensor* out__iter_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* out__iter_v1 = reinterpret_cast<__gm__ float*>(out__iter_v1_tensor->buffer.addr) + out__iter_v1_tensor->start_offset;

    // Unpack scalar: out_m0__ssa_v0
    union { uint64_t u64; int64_t val; } out_m0__ssa_v0_conv;
    out_m0__ssa_v0_conv.u64 = args[3];
    int64_t out_m0__ssa_v0 = out_m0__ssa_v0_conv.val;

    // Forward to ptoas-generated function
    paged_rmsnorm__windowed(gamma__ssa_v0, y_src__ssa_v0, out__iter_v1, out_m0__ssa_v0);
}
